import fs from 'node:fs';
import path from 'node:path';
import * as audit from '../audit.mjs';

export async function auditScenarios({check,mkServer,projDir,TMP,SERVER,AUDIT_META}){
 const old=process.env.ZCODE_BRIDGE_RUNTIME_ROOT;process.env.ZCODE_BRIDGE_RUNTIME_ROOT=path.join(TMP,'audit-runtime');
 const p=projDir('audit-cases'),tid='audit-task';
 const evidence=path.join(p,'evidence.txt');fs.writeFileSync(evidence,'verified command output: fixture');
 const rejects=(label,fn)=>{try{fn();check(label,false);}catch{check(label,true);}};
 const req=n=>({run_id:'run-'+n,model:'GLM-5.3',mode:'edit',phase:1,followup_kind:n===1?'initial':'repair'});
 const finding=(key,assessment='VERIFIED',priority='P1',status='open')=>({finding_key:key,title:'fixture finding',assessment,priority,status,category:'logic_bug',...(assessment==='VERIFIED'?{evidence:{description:'fixture evidence',files:[evidence]}}:{})});
 const review=(n,findings=[],verdict='NEEDS_FIX',executor='zcode')=>({task_id:tid,run_id:'run-'+n,round:n,findings,verdict,executor,validation_files:[evidence]});
 const final=()=>({task_id:tid,final_status:'PASS',acceptance_met:true,validation_files:[evidence],build_result:{status:'N/A',summary:'no build'},test_result:{status:'PASS',summary:'fixture assertions'},runtime_result:{status:'FAKE_ONLY',summary:'no model'},manual_interventions:[],good_performance:[],exposed_problems:[],model_observations:[],agent_observations:[],product_observations:[],mcp_observations:[],requirement_observations:[],zhipu_feedback:[]});
 console.log('\n[25] audit 必填、事件、轮次和 Review 不可覆盖');
 rejects('缺 audit 拒绝',()=>audit.validateMetadata(null));
 audit.begin(p,tid,req(1),AUDIT_META,'core brief');
 check('task.json 自动存在',fs.existsSync(path.join(audit.auditRoot(p),tid,'task.json')));
 check('round-01 自动存在',fs.existsSync(path.join(audit.auditRoot(p),tid,'rounds','round-01.json')));
 rejects('运行中不接受 Review',()=>audit.review(p,review(1)));
 audit.terminal(p,tid,'run-1','returned',[evidence]);
 rejects('未 Review 不允许续聊',()=>audit.preflight(p,tid));
 rejects('VERIFIED 缺 evidence 拒绝',()=>audit.review(p,review(1,[{...finding('bug'),evidence:null}])));
 rejects('Review 非当前 run 拒绝',()=>audit.review(p,{...review(1),run_id:'wrong'}));
 audit.review(p,review(1,[finding('bug'),finding('fp','FALSE_POSITIVE'),finding('design','DESIGN'),finding('likely','LIKELY')]));
 rejects('Review 不可覆盖',()=>audit.review(p,review(1)));
 let stats=audit.statistics(audit.readAudit(p,tid).events);
 check('FALSE_POSITIVE 与 VERIFIED 分开',stats.VERIFIED===1&&stats.FALSE_POSITIVE===1);
 check('LIKELY/DESIGN 不计优先级错误数',stats.P1===1&&stats.LIKELY===1&&stats.DESIGN===1);
 rejects('P0/P1 未解决不允许 PASS',()=>audit.finalize(p,final()));
 console.log('\n[26] 修复轮次、关联问题、覆盖授权和 regression');
 for(let n=2;n<=4;n++){
  const phase=audit.preflight(p,tid);check('修复 '+n+' phase 保持',phase===1);
  audit.begin(p,tid,req(n),null,'repair');audit.terminal(p,tid,'run-'+n,'returned',[evidence]);
  audit.review(p,review(n,[finding('bug','VERIFIED','P1',n===3?'regression':'not_fixed')]));
 }
 const events=audit.readAudit(p,tid).events;
 check('followup round 自动递增',events.filter(e=>e.type==='followup_started').map(e=>e.data.round).join(',')==='2,3,4');
 check('followup 关联上一轮 Review',events.find(e=>e.type==='followup_started').data.previous_review!==null);
 check('要求修复的问题关联 finding_key',events.find(e=>e.type==='followup_started').data.requested_finding_keys.includes('bug'));
 rejects('三次修复后阻止续聊',()=>audit.preflight(p,tid));
 audit.preflight(p,tid,'repair','用户明确授权继续一次');
 audit.begin(p,tid,{...req(5),override_authorization:'用户明确授权继续一次'},null,'repair');audit.terminal(p,tid,'run-5','returned',[evidence]);
 audit.review(p,review(5,[finding('bug','VERIFIED','P1','fixed')],'PASS'));
 stats=audit.statistics(audit.readAudit(p,tid).events);
 check('跨轮问题去重',stats.VERIFIED===1);
 check('自主修复必须后续验证',stats.autonomous_fixes===1);
 check('Regression 单独统计',stats.regressions===1);
 check('覆盖授权进入事件',audit.readAudit(p,tid).events.some(e=>e.type==='repair_limit_overridden'));
 check('阶段切换不占修复轮次',audit.preflight(p,tid,'phase')===2);
 console.log('\n[27] finalize 证据约束、服务器统计、报告完整性');
 rejects('acceptance_met=false 拒绝 PASS',()=>audit.finalize(p,{...final(),acceptance_met:false}));
 const out=audit.finalize(p,{...final(),statistics:{VERIFIED:999}});
 check('统计由服务器计算',out.statistics.VERIFIED===1);
 rejects('final 不可覆盖',()=>audit.finalize(p,final()));
 rejects('final 后不允许续聊',()=>audit.preflight(p,tid));
 const first=JSON.stringify(audit.report(p));check('报告重复生成稳定',first===JSON.stringify(audit.report(p)));
 fs.writeFileSync(evidence,'tampered');check('证据哈希发现篡改',audit.report(p).items[0].changed_evidence.includes(evidence));
 const bad=path.join(audit.auditRoot(p),'bad-audit');fs.mkdirSync(bad);fs.writeFileSync(path.join(bad,'events.jsonl'),'{bad\n');
 check('损坏任务不拖垮统计',audit.report(p).items.length===1&&audit.report(p).corrupted.includes('bad-audit'));
 check('支持月份过滤',audit.report(p,'2000-01').items.length===0);
 const eid='no-evidence';audit.begin(p,eid,{run_id:'e1',mode:'edit',model:'GLM-5.3'},AUDIT_META,'fixture');audit.terminal(p,eid,'e1','returned');
 audit.review(p,{task_id:eid,run_id:'e1',round:1,verdict:'PASS',executor:'codex',findings:[]});
 rejects('PASS 无客观验证拒绝',()=>audit.finalize(p,{...final(),task_id:eid,validation_files:[]}));
 const partial=audit.finalize(p,{...final(),task_id:eid,validation_files:[],final_status:'PARTIAL',acceptance_met:false});
 check('人工接手自动计数',partial.statistics.manual_interventions===1);
 console.log('\n[28] 历史补录不进入表现比率、审计链接边界');
 const hid='historical';audit.begin(p,hid,{run_id:'h1',mode:'edit',model:'UNKNOWN'},AUDIT_META,'UNKNOWN',{historical:true});audit.terminal(p,hid,'h1','returned');
 audit.review(p,{task_id:hid,run_id:'h1',round:1,verdict:'PASS',executor:'unknown',findings:[],validation_files:[evidence]});audit.finalize(p,{...final(),task_id:hid});
 const report=audit.report(p);check('历史任务单列',report.totals.historical_tasks===1&&report.totals.tasks===2);
 check('历史首次通过未知',report.items.find(x=>x.task_id===hid).statistics.first_pass===null);
 const outside=projDir('audit-outside'),link=path.join(audit.auditRoot(p),'linked');fs.symlinkSync(outside,link,'junction');
 rejects('审计 task Junction 越界拒绝',()=>audit.begin(p,'linked',{run_id:'x'},AUDIT_META,'x'));fs.rmdirSync(link);
 console.log('\n[29] MCP 新进程 schema 与真实 fake CLI 生命周期');
 const srv=mkServer();await srv.init();const project=projDir('audit-mcp');
 const raw=async(name,args)=>(await srv.call('tools/call',{name,arguments:args}));
 const missing=await raw('zcode_start',{project_dir:project,prompt:'@fake:mode=ok'});check('MCP start 缺 audit 拒绝',missing.isError===true);
 const start=await raw('zcode_start',{project_dir:project,prompt:'@fake:mode=ok',audit:{...AUDIT_META,task_name:'secret SUPER-SECRET-SENTINEL-123'}});
 check('MCP start 带 audit 接受',!!start.structuredContent?.run_id);const id=start.structuredContent.task_id;
 let w;do{w=await raw('zcode_wait',{project_dir:project,task_id:id,timeout_ms:3000});}while(w.structuredContent?.still_running);
 const rr=await raw('zcode_record_review',{project_dir:project,task_id:id,run_id:start.structuredContent.run_id,round:1,verdict:'PASS',executor:'codex',findings:[],validation_files:[path.join(project,'.zcode-mcp','runs',start.structuredContent.run_id,'result.json')]});
 check('MCP record_review 成功',rr.structuredContent?.recorded===true);
 const fin=await raw('zcode_finalize',{...final(),project_dir:project,task_id:id,validation_files:[],model_observations:['SUPER-SECRET-SENTINEL-123']});
 check('MCP finalize 成功',fin.structuredContent?.final_status==='PASS');
 process.env.ZCODE_BRIDGE_RUNTIME_ROOT=path.join(TMP,'runtimes');
 const rawLog=JSON.stringify(audit.readAudit(project,id));check('审计不含 API Key',!rawLog.includes('SUPER-SECRET-SENTINEL-123'));
 check('报告不含 API Key',!JSON.stringify(audit.report(project)).includes('SUPER-SECRET-SENTINEL-123'));
 check('finalize 自动生成报告',fs.existsSync(path.join(project,'docs','ZCODE_EXPERIENCE_STATS.json')));
 console.log('\n[30] v1.3.1 权威任务显式迁移');
 const migrationDir=path.join(audit.auditRoot(project),id);fs.rmSync(migrationDir,{recursive:true,force:true});
 const migrated=await raw('zcode_record_review',{project_dir:project,task_id:id,run_id:start.structuredContent.run_id,round:1,verdict:'PASS',executor:'unknown',findings:[],validation_files:[path.join(project,'.zcode-mcp','runs',start.structuredContent.run_id,'result.json')],migration_audit:AUDIT_META});
 check('已有权威任务可显式补录',migrated.structuredContent?.recorded===true);
 check('迁移历史不伪造首次通过',migrated.structuredContent?.statistics.first_pass===null);
 check('迁移标记缺失历史',audit.readAudit(project,id).task.unknown_history===true);
 srv.kill();
 console.log('\n[31] 隔离主机定位配置 + fake CLI');
 const oldLocalAppData=process.env.LOCALAPPDATA;
 const localFixture=path.join(TMP,'host-localappdata');
 const fixtureAuthority=path.join(TMP,'host-authority');
 fs.mkdirSync(path.join(localFixture,'zcode-mcp-bridge'),{recursive:true});
 fs.writeFileSync(path.join(localFixture,'zcode-mcp-bridge','authority-location.json'),JSON.stringify({root:fixtureAuthority}));
 process.env.LOCALAPPDATA=localFixture;
 delete process.env.ZCODE_BRIDGE_RUNTIME_ROOT;
 const host=mkServer({ZCODE_BRIDGE_RUNTIME_ROOT:''});await host.init();const hp=projDir('host-root');
 const started=await host.tool('zcode_start',{project_dir:hp,prompt:'@fake:mode=inspect'});
 check('主机根可原子写控制/审计',!started.isError);
 if(!started.isError){let state;do{state=await host.tool('zcode_wait',{project_dir:hp,task_id:started.sc.task_id,timeout_ms:3000});}while(state.sc?.still_running);
  check('主机根 fake CLI 返回',state.sc?.status==='returned');
  check('新项目CLI runtime使用配置主机根',JSON.parse(state.sc.result.response).storage===path.join(audit.baseRoot(),audit.projectHash(hp)));
  check('主机根终态审计存在',audit.readAudit(hp,started.sc.task_id).events.some(e=>e.type==='run_returned'));
 }
 host.kill();
 if(oldLocalAppData===undefined)delete process.env.LOCALAPPDATA;else process.env.LOCALAPPDATA=oldLocalAppData;
 console.log('\n[32] 竞争续聊只允许一个 run');
 const race=mkServer(),rp=projDir('race');await race.init();
 const raceStart=await race.tool('zcode_start',{project_dir:rp,prompt:'@fake:mode=ok'});let done;do{done=await race.tool('zcode_wait',{project_dir:rp,task_id:raceStart.sc.task_id,timeout_ms:3000});}while(done.sc?.still_running);
 await race.tool('zcode_record_review',{project_dir:rp,task_id:raceStart.sc.task_id,run_id:raceStart.sc.run_id,round:1,verdict:'PASS',executor:'zcode',findings:[]});
 const contenders=await Promise.all([1,2].map(()=>race.call('tools/call',{name:'zcode_followup',arguments:{project_dir:rp,task_id:raceStart.sc.task_id,prompt:'@fake:mode=ok'}})));
 check('竞争续聊只接受一个',contenders.filter(x=>!x.isError).length===1);
 do{done=await race.tool('zcode_wait',{project_dir:rp,task_id:raceStart.sc.task_id,timeout_ms:3000});}while(done.sc?.still_running);
 check('被接受的 run 正常返回',done.sc?.status==='returned');race.kill();
 if(old===undefined)delete process.env.ZCODE_BRIDGE_RUNTIME_ROOT;else process.env.ZCODE_BRIDGE_RUNTIME_ROOT=old;
}
